### ISSUE TITLE
problem with many tags

### ISSUE THREAD

**Issue by TarasDerevianko** [yutannihilation/K9#8]
Please fix a bug in `k9_post_metric`. 

The syntax 
`series["tags"] <- I(tags)`
allows you to add only 1 tag

You can fix it using syntax like this
`series[["tags"]] <- I(tags)`

**Comment by yutannihilation** [comment]
Thanks! I really appreciate a PR for this since I no longer have Datadog acount now...

**Comment by DolciAlessandroSpring** [comment]
Hi I'm having problems even with one single tag, can you help me? :)

k9_post_metric(metric = 'name',
                           metric_type = 'gauge',
                           value = 1,
                           tags =  list('mytagname'))

I still see * in the tags in Datadog. Any clue?

**Comment by yutannihilation** [comment]
Closed by #9
